name: Docker Publish Latest

on:
  push:
    workflow_dispatch:
      inputs:
          candidate:
            description: Version candidate to be latest
            required: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}

jobs:
  buildTaggedVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the image name
        id: get_name
        run: echo ::set-output name=IMAGE_NAME::${REPO_NAME/docker-}

      - name: Build the tagged Docker image
        run: docker build --build-arg VERSION=${{ inputs.candidate }} --build-arg BUILD_DATE="$(date +%Y/%m/%dT%H:%M:%S)" --file Dockerfile --tag ${{ steps.get_name.outputs.IMAGE_NAME }}:latest .
      
      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: docker push ${{ steps.get_name.outputs.IMAGE_NAME }}:latest

